apiVersion: v1
kind: Pod
metadata:
  name: sleep-pod
  labels:
    app: sleep
spec:
  containers:
    - image: busybox
      command:
        - "sleep"
        - "60"
      imagePullPolicy: IfNotPresent
      name: sleep-container
  restartPolicy: Never